drop table TravellerDetails;


create table  T2(id number(10) GENERATED BY DEFAULT AS IDENTITY,name varchar2(25),doubt varchar2(25));


insert into TravellerDetails values(8,'hj','john123');

delete from hashmap_map;

drop table hashmap_map;

create table list1(name varchar2(25));

select * from starcountt;

delete from  list1;
insert into list1 values('TL3');

create table hashmap_map (k varchar(200), v varchar(200));

insert into SR3 values (1,'key','value');

insert into hashmap_map values ('hema','TL2');
insert into hashmap_map values ('hema1','TL3');
 CREATE SEQUENCE sq
    START WITH 1001
    INCREMENT BY 1
    MAXVALUE 100000000000000001;
   
create table filename( name clob);
    
select * from hashmap_map;

